name: kugoogle
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0

dev_dependencies:
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
